name = "constraints"
version = "0.7.3"
[dependencies]
stanza-utils = "jackbackrack/stanza-utils|0.1.1"
stanza-geom = "jackbackrack/stanza-geom|0.1.6"
stanza-gfx = "jackbackrack/stanza-gfx|0.1.6"
stanza-opencv = "jackbackrack/stanza-opencv|0.1.2"
stanza-gui = "jackbackrack/stanza-gui|0.1.1"
stanza-libfive = "jackbackrack/stanza-libfive|0.1.2"
stanza-asmjit = "jackbackrack/stanza-asmjit|0.1.3"
